#!/bin/bash

usage() {
  echo "Usage: ${self} options"
  echo "  -h help" 
  echo "  --provider-settings"
  echo "  --output-file"
  echo "  --dep-output-file"
  echo "  --rules"
  echo "  --label-selector"
  echo "  --dep-label-selector"
  echo "  --no-dependency-rules"
}

RULES=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --provider-settings)
      SETTINGS="$2"
      shift 2
      ;;
    --provider-settings=*)
      SETTINGS="${1#*=}"
      shift
      ;;
    --output-file)
      OUTPUT="$2"
      shift 2
      ;;
    --output-file=*)
      OUTPUT="${1#*=}"
      shift
      ;;
    --dep-output-file)
      DEP_OUTPUT="$2"
      shift 2
      ;;
    --dep-output-file=*)
      DEP_OUTPUT="${1#*=}"
      shift
      ;;
    --rules)
      RULES+=("$2")
      shift 2
      ;;
    --rules=*)
      RULES+=("${1#*=}")
      shift
      ;;
    --label-selector)
      LABEL_SELECTOR="$2"
      shift 2
      ;;
    --label-selector=*)
      LABEL_SELECTOR="${1#*=}"
      shift
      ;;
    --dep-label-selector)
      DEP_LABEL_SELECTOR="$2"
      shift 2
      ;;
    --dep-label-selector=*)
      DEP_LABEL_SELECTOR="${1#*=}"
      shift
      ;;
    --no-dependency-rules)
      NO_DEP_RULES="TRUE"
      shift
      ;;
    -h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

echo
echo "main:"
echo "  settings: ${SETTINGS}"
echo "     rules: ${RULES[*]}"
echo "    output: ${OUTPUT}"
echo "  selector: ${LABEL_SELECTOR}"
echo "dep:"
echo "  output: ${DEP_OUTPUT}"
echo "selector: ${DEP_LABEL_SELECTOR}"
echo "no rules: ${NO_DEP_RULES}"

if [[ -f "${ISSUES}" ]]
then
  cp ${ISSUES} ${OUTPUT}
fi

if [[ -f "${DEPS}" ]]
then
  cp ${DEPS} ${DEP_OUTPUT}
fi

echo
echo "DONE"

